# Generated by Django 3.2.9 on 2021-12-03 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readend',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='read_end', to='posts.subscriptions', verbose_name='Просмотренный пост'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='readend',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_end', to='posts.post', verbose_name='Прочтианый пост писателя'),
        ),
        migrations.DeleteModel(
            name='AddReadEnd',
        ),
    ]
