# Generated by Django 3.2.9 on 2022-01-19 13:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20211203_1512'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readend',
            unique_together={('author', 'subscription', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='subscriptions',
            unique_together={('subscriber', 'writer')},
        ),
    ]
