version: '3.3'

volumes:

  postgres_data:
  static_value:

services:

  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env


  backend:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_value:/app/static/
    depends_on:
      - db
    env_file:
      - .env
